
networks:
  counter1:

services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - counter1
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    scale: 2
    ports:
      - "6379"
    networks:
      counter1:
    command: ["redis-server", "--loglevel", "verbose"]

